# Generated by Django 3.1.3 on 2020-12-02 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(max_length=1024, null=True, upload_to='avatars/'),
        ),
    ]
