# Generated by Django 3.1.3 on 2020-11-27 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rssCollector', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webnews',
            name='header',
            field=models.CharField(default='Heading', max_length=256),
        ),
    ]
