# Generated by Django 3.1.3 on 2020-11-28 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rssCollector', '0002_webnews_header'),
    ]

    operations = [
        migrations.RenameField(
            model_name='webnews',
            old_name='date',
            new_name='publish_date',
        ),
    ]
