# Generated by Django 3.1.3 on 2020-12-05 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rssCollector', '0006_auto_20201206_0249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webnews',
            name='body',
            field=models.TextField(default='', null=True),
        ),
    ]
